"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { createStatistics } = require("../lib/statistics");
const directory = fs.mkdtempSync(path.join(os.tmpdir(), "automining-statistics-"));
const filename = path.join(directory, "statistics.json");
let now = Date.UTC(2026, 8, 27, 12), next = 0, reads = 0;
const rows = [];
let fleet = { fleetID: 5, members: new Map([[42, {}], [43, {}]]) };
const options = { clock: () => now, typeVolume: () => 0.1, isDroneType: id => id === 900,
  getFleet: () => fleet, getSession: () => ({}), characterName: id => `Pilot ${id}` };
const ledger = { recordMiningLedgerEvent(event) {
  const data = { ...event, entryID: ++next, eventDateMs: now };
  rows.push(data); return { success: true, data };
}, getCharacterMiningLogs(id) { reads++; return rows.filter(row => row.characterID === id).slice().reverse(); } };
const session = { characterID: 42 }, other = { characterID: 43 };
const stats = createStatistics(filename, options);
stats.attachLedger(ledger);
assert.equal(fs.existsSync(filename), false, "Require/attach must not persist or start a timer");
now += 1000;
const result = ledger.recordMiningLedgerEvent({ characterID: 42, typeID: 123, moduleTypeID: 800, quantity: 100, quantityWasted: 7, quantityCritical: 30 });
ledger.recordMiningLedgerEvent({ characterID: 42, typeID: 123, moduleTypeID: 900, quantity: 50 });
assert.equal(stats.ingest(result.data), false, "Same native entry cannot count twice");
let total = stats.snapshot(session).totals;
assert.equal(total.units, 150); assert.equal(total.volume, 15);
assert.equal(total.moduleVolume, 10); assert.equal(total.droneVolume, 5);
assert.equal(total.wastedUnits, 7); assert.equal(total.deliveries, 2);
stats.snapshot(session); stats.snapshot(session);
assert.equal(reads, 1, "No full ledger rescan per HUD refresh");
assert.equal(stats.observeDock(session, 600, 600), false);
assert.equal(stats.observeDock(session, 0, 600), true);
assert.equal(stats.observeDock(session, 0, 600), false);
stats.observeDock(session, 600, 0);
assert.equal(stats.observeDock(session, 0, 600), true);
assert.equal(stats.recordTrip(session, "trip-1"), true);
assert.equal(stats.recordTrip(session, "trip-1"), false);
assert.equal(stats.snapshot(session).totals.docks, 2);
assert.equal(stats.snapshot(session).totals.trips, 1);
ledger.recordMiningLedgerEvent({ characterID: 43, typeID: 123, moduleTypeID: 900, quantity: 20 });
assert.equal(stats.snapshot(session, { view: "fleet" }).totals.units, 170);
const otherBefore = stats.snapshot(other).totals.units;
now += 60000;
stats.resetRun(session);
assert.equal(fs.existsSync(filename), true, "Archive must persist immediately");
assert.equal(stats.snapshot(session).totals.units, 0);
assert.equal(stats.snapshot(other).totals.units, otherBefore, "Reset must not reset fleet peers");
assert.equal(stats.sessions(session).rows[0].totals.units, 150);
assert.equal(stats.sessions(session).rows[0].totals.docks, 2);
assert.equal(stats.snapshot(session, { period: "tracked" }).totals.units, 150);
fleet.members.delete(42);
assert.equal(stats.snapshot(session, { view: "fleet" }).inFleet, false, "Removed fleet member loses operation access");
const recovered = createStatistics(filename, options);
recovered.attachLedger({ ...ledger, recordMiningLedgerEvent: event => ({ success: false }) });
assert.equal(recovered.snapshot(session).totals.units, 0);
assert.equal(recovered.sessions(session).rows[0].totals.units, 150);
stats.flush(); recovered.flush();
fs.rmSync(directory, { recursive: true, force: true });
console.log("PASS: module/drone yield, critical/waste separation, idempotence, bounded recovery, dock/trip counts, fleet authorization, durable run reset/history.");
